### ISSUE TITLE
error when loading the background picture

### ISSUE THREAD

**Issue by Ashaxer** [CodeXTF2/qtscrcpy_keymap_editor#1]
GREAT JOB! Loved your work!
Still I get an error when loading the background picture:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Shaxius\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Portable Apps\QtScrcpy-Keymap-Editor\keymap.py", line 57, in load_background_image
    img = img.resize((1920, 1080), Image.ANTIALIAS)
                                   ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by Ashaxer** [comment]
Changing ```Image.ANTIALIAS``` to ```Image.LANCZOS``` at line 57 fixed my issue

**Comment by CodeXTF2** [comment]
Done. Thanks for the fix!
